### ISSUE TITLE
Compatibility with nextcloud 18

### ISSUE THREAD

**Issue by neddstark** [undo-ransomware/ransomware_detection#28] opened 2020-03-10 10:16 UTC
This app is reported as incompatible with nextcloud 18.

**Comment by Zocker1999NET** [comment] 2020-03-20 08:19
Duplicate of #27 I think

**Comment by neddstark** [comment] 2020-03-20 11:36
indeed it's duplicate of #27 but I was hoping for more visibility for the maintainer, to speed up releasing this for nextcloud 18

**Comment by SimJoSt** [comment] 2020-03-23 20:59
That's a nice idea, but I don't think it is helpful :)  
One issue should suffice and is better for not cluttering the repo ;)

**Comment by ilovemilk** [comment] 2020-03-24 19:48
I will make some time to work on this app this week. I will evaluate the compatibility and release a new version! I will get back to you in #27.

**Closed by ilovemilk** 2020-03-24 19:48 UTC
